version: '3.8'

services:
  scraper:
    build: .
    container_name: scraper_fcf_sc
    volumes:
      - ./scraper_fcf.py:/app/scraper_fcf.py
      # - ./scraper_fcf.py:/app/test.py
    # environment:
    #   - PYTHONUNBUFFERED=1
    env_file: ".env"
    # Uncomment to run in interactive mode
    # stdin_open: true
    # tty: true